"""empty message

Revision ID: 1220d51481c5
Revises: 8ced6d533000
Create Date: 2023-08-16 09:00:28.025414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1220d51481c5"
down_revision = "8ced6d533000"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("artists", schema=None) as batch_op:
        batch_op.drop_column("past_shows_count")
        batch_op.drop_column("upcoming_shows_count")

    with op.batch_alter_table("venues", schema=None) as batch_op:
        batch_op.drop_column("past_shows_count")
        batch_op.drop_column("upcoming_shows_count")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("venues", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "upcoming_shows_count",
                sa.INTEGER(),
                autoincrement=False,
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column(
                "past_shows_count", sa.INTEGER(), autoincrement=False, nullable=False
            )
        )

    with op.batch_alter_table("artists", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "upcoming_shows_count",
                sa.INTEGER(),
                autoincrement=False,
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column(
                "past_shows_count", sa.INTEGER(), autoincrement=False, nullable=False
            )
        )

    # ### end Alembic commands ###
