"""empty message

Revision ID: 37c63cf25742
Revises: 1220d51481c5
Create Date: 2023-08-16 09:47:50.120665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37c63cf25742'
down_revision = '1220d51481c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shows', schema=None) as batch_op:
        batch_op.alter_column('venue_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('artist_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('artist_image_link')
        batch_op.drop_column('venue_name')
        batch_op.drop_column('artist_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shows', schema=None) as batch_op:
        batch_op.add_column(sa.Column('artist_name', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('venue_name', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('artist_image_link', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.alter_column('artist_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('venue_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
